version: '3.8'

services:
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - '9000:9000'
            - '9001:9001'
        environment: 
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data

    dynamodb:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb
        ports:
            - '8000:8000'
        volumes:
            - dynamodb_data:/data

    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        container_name: dynamodb-admin
        ports:
            - '8001:8001'
        environment:
            DYNAMO_ENDPOINT: ${DYNAMO_ENDPOINT}
        depends_on:
            - dynamodb

volumes:
    minio_data:
    dynamodb_data:
